version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password123
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password123
  github-4:
    build:
      context: git@github.com:Runnabtle/SAN-6325-test.git#gihtub-repo-test
      dockerfile: ./Dockerfile.server
    command: "echo github-git try 15"
