version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  github-3:
    build:
      context: git@github.com:Runnabtle/SAN-6325-test.git#branch-that-doesnt-exist
      dockerfile: ./Dockerfile.client
    command: "echo github-git try 15"

  github-4:
    build:
      context: git@github.com:Runnabtle/SAN-6325-test.git#gihtub-repo-test
      dockerfile: ./Dockerfile.server
    command: "echo github-git try 15"
