version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server

  client:
    build:
      context: .
      dockerfile: ./Dockerfile.client

  --rethinkdb:
    image: rethinkdb:latest

  99mongo:
    image: mongo:latest

  pgsql:
    image: postgres:latest
