version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.ecr

  ecr2:
    image: 437258487404.dkr.ecr.us-west-2.amazonaws.com/jorge/kube-nginx-letsencrypt:hello10
