version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  github-git:
    build:
      context: git@github.com:Runnable/SAN-6325-test.git#gihtub-repo-test
      dockerfile: ./Dockerfile.client
    command: "echo github-git try 13"

  github-http:
    build:
      context: https://github.com/CodeNow/big-poppa.git
      dockerfile: ./Dockerfile_test
    command: "echo github-http try 13"

  github-3:
    build:
      context: git@github.com:Runnabtle/SAN-6325-test.git#gihtub-repo-test
      dockerfile: ./Dockerfile.server
    command: "echo github-git try 13"
