version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.ecr

  ecr_client:
    build:
      context: .
      dockerfile: ./Dockerfile.client  

  ecr_server:
    build:
      context: .
      dockerfile: ./Dockerfile.server