version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.server

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    command: sleep 99999
    links:
    - main:consul.zd-dev.com
    environment:
    - HOST=consul.zd-dev.com
