version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  github-git:
    build:
      context: git@github.com:Runnable/SAN-6325-test.git
      dockerfile: ./Dockerfile.busybox
    command: "echo github-git try 3"

  github-http:
    build:
      context: https://github.com/Runnable/SAN-6325-test.git
      dockerfile: ./Dockerfile.busybox
    command: "echo github-http try 3"
