version: '2'
services:
  main3000: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.server

  main80:
    build:
      context: .
      dockerfile: ./Dockerfile.server2

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    command: sleep 99999
    links:
    - main80:consul.zd-dev.com
    - main3000
    environment:
    - HOST=consul.zd-dev.com
