version: '2'
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile.python
    links:
    - consul
    - memcached
    environment:
    - CONSUL_HOST=consul

  consul:
    image: consul:0.7.5
    command: consul agent -bind 127.0.0.1 -config-dir /consul/data -dc dev1 -server -ui -bootstrap-expect 1 -client 0.0.0.0 -data-dir /consul/data
    ports:
     - "8300:8300"
     - "8400:8400"
     - "8500:8500"
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
      - CONSUL_VERSION=0.7.5

  memcached:
    build:
      context: .
      dockerfile: ./Dockerfile.memcached
    command: bash register_to_consul.bash
    links:
    - consul
    ports:
      - "11211:11211"
