version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  github-http:
    build:
      context: git@github.com:Runnable/SAN-6325-test.git
      dockerfile: ./Dockerfile.ecr
