version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.ecr

  wow:
    build:
      context: git@github.com/Runnable/SAN-6325-test.git

  # wow2:
    # build:
      # context: git@github.com/Runnable/SAN-6325-test.git#35ad725a54f7675c7b139dd9e5caf9eb284130bd

  test2:
    build:
      context: git@github.com/CodeNow/DockerizeRepo1.git

  test1:
    build:
      context: git@github.com/CodeNow/DockerizedRepo2.git
