version: '2'
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    links:
      - server
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./Dockerfile

  github:
    build: https://github.com/Runnable/SAN-6325-test
