version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password123
  ecr_@&#^$*:
    build:
      context: .
      dockerfile: ./Dockererer
