version: '2'
services:
  main: # One service with build with the same service name must be kept
    build:
      context: .
      dockerfile: ./Dockerfile.busybox

  ecr:
    build:
      context: .
      dockerfile: ./Dockerfile.ecr

  wow:
    build:
      context: git@github.com/CodeNow/DockerizeRepo1.git

  test2:
    build:
      context: git@github.com/CodeNow/DockerizeRepo1.git

  test1:
    build:
      context: git@github.com/CodeNow/DockerizedRepo2.git#taylor-test
